### ISSUE TITLE
Support Amazon Elasticsearch Service

### ISSUE THREAD

**Issue by muga** [embulk/embulk-output-elasticsearch#24]
http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html

**Comment by relaxteatime** [comment]
AWS Elasticsearch Service support VPC.
https://forums.aws.amazon.com/ann.jspa?annID=5070

HTTPS access not requiring authentication.

I hope that it will be supported.

ex.
For the domain of AWS ES, I hope to issue a warning log instead of an error.

**Comment by sakama** [comment]
@relaxteatime Sorry to be late.
We changed implementation to show warning message instead of throwing Exception
https://github.com/embulk/embulk-output-elasticsearch/pull/49
You won't get such Exception at v0.4.7.

Thanks.
